# Generated by Django 6.0.2 on 2026-02-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='current_step',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
