# Generated by Django 6.0.2 on 2026-03-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_current_step_lead_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedEmail',
            fields=[
                ('call_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
